#import "../mgn901-paper/utils.typ": q

#let font-settings-presets = (
  serif: (
    font-family: (
      latin: ("Nimbus Roman", "Times New Roman", "Century", "Libertinus Serif", "New Computer Modern"),
      cjk: (
        "Source Han Serif JP",
        "Noto Serif CJK JP",
        "Hiragino Mincho Pr6N",
        "Hiragino Mincho ProN",
        "YuMincho",
        "Yu Mincho",
        "MS Mincho",
      ),
    ),
    font-weight: 400,
    font-features: (:),
  ),
  sans: (
    font-family: (
      latin: ("Helvetica Neue", "Helvetica", "Arial"),
      cjk: (
        "Source Han Sans JP",
        "Noto Sans CJK JP",
        "Hiragino Sans",
        "YuGothic",
        "Yu Gothic",
        "MS Gothic",
      ),
    ),
    font-weight: 500,
    font-features: (:),
  ),
  heading: (
    font-family: (
      latin: ("Helvetica Neue", "Helvetica", "Arial"),
      cjk: (
        "Source Han Sans JP",
        "Noto Sans CJK JP",
        "Hiragino Sans",
        "YuGothic",
        "Yu Gothic",
        "MS Gothic",
      ),
    ),
    font-weight: 700,
    font-features: (:),
  ),
  monospace: (
    font-family: (
      latin: ("Courier New", "Dejavu Sans Mono"),
      cjk: (
        "Source Han Sans JP",
        "Noto Sans CJK JP",
        "Hiragino Sans",
        "YuGothic",
        "Yu Gothic",
        "MS Gothic",
      ),
    ),
    font-weight: 400,
    font-features: (:),
  ),
)

#let font-settings-presets-paper = (
  default: font-settings-presets.serif,
  heading: font-settings-presets.heading,
  footnote: font-settings-presets.serif,
  small: font-settings-presets.serif,
  monospace: font-settings-presets.monospace,
  strong: font-settings-presets.sans,
)

#let color-presets = (
  blue: (
    rgb("#f2f8ff"),
    rgb("#e3f4ff"),
    rgb("#c7e7ff"),
    rgb("#9fd1ff"),
    rgb("#6eb3ff"),
    rgb("#3890ff"),
    rgb("#006af5"),
    rgb("#0050bb"),
    rgb("#00367e"),
    rgb("#001c43"),
    rgb("#00050d"),
  ),
  green: (
    rgb("#f2fff9"),
    rgb("#d5fcea"),
    rgb("#b0f3d8"),
    rgb("#83e4c1"),
    rgb("#54cfa9"),
    rgb("#27b590"),
    rgb("#009575"),
    rgb("#007352"),
    rgb("#004e32"),
    rgb("#002b19"),
    rgb("#000d06"),
  ),
  red: (
    rgb("#fff4f2"),
    rgb("#ffede8"),
    rgb("#ffd9d3"),
    rgb("#ffbab2"),
    rgb("#ff9289"),
    rgb("#f1625b"),
    rgb("#dd302c"),
    rgb("#c50000"),
    rgb("#850700"),
    rgb("#460800"),
    rgb("#0d0200"),
  ),
  yellow: (
    rgb("#fffdf2"),
    rgb("#fff9d9"),
    rgb("#fbefb6"),
    rgb("#f1df8b"),
    rgb("#e1c85b"),
    rgb("#caad2b"),
    rgb("#af8e00"),
    rgb("#866e00"),
    rgb("#5b4b00"),
    rgb("#312900"),
    rgb("#0d0b00"),
  ),
  gray1: (
    rgb("#ffffff"),
    rgb("#fcfbfa"),
    rgb("#f4f2ef"),
    rgb("#e5e2de"),
    rgb("#d0ccc8"),
    rgb("#b5b1ac"),
    rgb("#94908b"),
    rgb("#6f6c67"),
    rgb("#474542"),
    rgb("#21201e"),
    rgb("#000000"),
  ),
  gray2: (
    rgb("#ffffff"),
    rgb("#f8fafc"),
    rgb("#eceff4"),
    rgb("#dadee5"),
    rgb("#c3c7d0"),
    rgb("#a7acb5"),
    rgb("#888c94"),
    rgb("#65686f"),
    rgb("#414347"),
    rgb("#1e1f21"),
    rgb("#000000"),
  ),
)
