#import "../mgn901-paper/utils.typ": q
#import "common.typ": color-style-tokens

#let interFontCovers = regex(
  "[ -~ -¬®-ňŊ-ǃǅ-ɔɖ-ɨɪ-ɻɾ-ʄʆ-ʐʒ-ʤʦ-ʻʽ-˭˯-̄̆-̛̣̦̊̌̏̓̕-̷̨̬-̸͂-̓͆-ͯʹ-Ͷͺ-Ϳ΄-ΊΌΎ-ΡΣ-ϗϜ-ϝϰ-϶Ϲ-Ϻϼ-ѹҀ-ҝҠ-ӿԯ฿ᴀᴍᴛᵃᵇ-ᵉᵍᵏ-ᵐᵒᵖ-ᵘᵛᵢ-ᵥᶜᶠᶻᶿ-᷵᷼-ẛẝ-ἕἘ-Ἕἠ-ὅὈ-Ὅὐ-ὗὙὛὝὟ-ώᾀ-ᾴᾶ-ῄῆ-ΐῖ-Ί῝-`ῲ-ῴῶ-῾ -​‐-‧ -⁕⁗ ⁰-ⁱ⁴-₎ₐ-ₜ₠-₯₱-₵₸-₺₼-⃀⃛-⃞⃨⃰℀-℁℃℅-℆℉ℓ№-℗℞-™K-Å℮Ⅎ℻⅍⅐-ⅿↃ-ↆ↉←-↙↩-↪↰-↱↳-↵↺-↻⇐⇒⇔⇞-⇟⇤-⇥⇧⇪∂∅∏∑-−√∞∫∶≈≠≤-≥⊕-⊘⌃-⌅⌘⌥-⌧⌫⎀⎇⎋⏎-⏏␣①-⑨Ⓐ-Ⓩ⓪■-▢▪▲-△▷►▼-▽◀-◁◆-◇◊-○●◦◯☀★-☆☼♡♥♪-♫⚠✓✗❖❤⟯⟵-⟺⤓⨸⬆⬒-⬓⬜⬤ⱼⱿⷿ⸘ꚟꟿ꤮----------------------]",
)

#let page-settings = (
  width: 210mm,
  height: 297mm,
  column-numbers: 2,
  column-gap: 3em,
  line-length: 26,
  line-numbers: 50,
  nombre: true,
)

#let style-tokens = (
  gap-0: (gap: 0em),
  gap-5: (gap: q(6)),
  gap-10: (gap: q(8)),
  gap-15: (gap: q(10)),
  gap-20: (gap: q(12)),
  gap-25: (gap: q(14)),
  gap-30: (gap: q(16)),
  gap-35: (gap: q(18)),
  gap-40: (gap: q(20)),
  gap-x-0: (gap-x: 0em),
  gap-x-5: (gap-x: q(6)),
  gap-x-10: (gap-x: q(8)),
  gap-x-15: (gap-x: q(10)),
  gap-x-20: (gap-x: q(12)),
  gap-x-25: (gap-x: q(14)),
  gap-x-30: (gap-x: q(16)),
  gap-x-35: (gap-x: q(18)),
  gap-x-40: (gap-x: q(20)),
  gap-y-0: (gap-y: 0em),
  gap-y-5: (gap-y: q(6)),
  gap-y-10: (gap-y: q(8)),
  gap-y-15: (gap-y: q(10)),
  gap-y-20: (gap-y: q(12)),
  gap-y-25: (gap-y: q(14)),
  gap-y-30: (gap-y: q(16)),
  gap-y-35: (gap-y: q(18)),
  gap-y-40: (gap-y: q(20)),
  inset-0: (inset: 0em),
  inset-5: (inset: q(6)),
  inset-10: (inset: q(8)),
  inset-15: (inset: q(10)),
  inset-20: (inset: q(12)),
  inset-25: (inset: q(14)),
  inset-30: (inset: q(16)),
  inset-35: (inset: q(18)),
  inset-40: (inset: q(20)),
  outset-0: (outset: 0em),
  outset-5: (outset: q(6)),
  outset-10: (outset: q(8)),
  outset-15: (outset: q(10)),
  outset-20: (outset: q(12)),
  outset-25: (outset: q(14)),
  outset-30: (outset: q(16)),
  outset-35: (outset: q(18)),
  outset-40: (outset: q(20)),
  font-sans: (
    font-family: (
      (
        name: "Inter",
        covers: interFontCovers,
      ),
      "A P-OTF UD Shin Go Pr6N L",
      "Source Han Sans JP",
    ),
    font-features: (ss01: 1, ss02: 1, ss03: 1, zero: 1, tnum: 1),
  ),
  font-serif: (
    font-family: (
      (
        name: "Inter",
        covers: interFontCovers,
      ),
      "A P-OTF UD Shin Go Pr6N L",
      "Source Han Sans JP",
    ),
    font-features: (ss01: 1, ss02: 1, ss03: 1, zero: 1, tnum: 1),
  ),
  font-mono: (
    font-family: ("Roboto Mono", "Source Han Sans JP"),
    font-features: (:),
  ),
  font-normal: (
    font-family: (
      (
        name: "Inter",
        covers: interFontCovers,
      ),
      "A P-OTF UD Shin Go Pr6N L",
      "Source Han Sans JP",
    ),
    font-features: (ss01: 1, ss02: 1, ss03: 1, zero: 1, tnum: 1),
    font-weight: 300,
  ),
  font-medium: (
    font-family: (
      (
        name: "Inter",
        covers: interFontCovers,
      ),
      "A P-OTF UD Shin Go Pr6N R",
      "Source Han Sans JP",
    ),
    font-features: (ss01: 1, ss02: 1, ss03: 1, zero: 1, tnum: 1),
    font-weight: 400,
  ),
  font-semibold: (
    font-family: (
      (
        name: "Inter",
        covers: interFontCovers,
      ),
      "A P-OTF UD Shin Go Pr6N DB",
      "Source Han Sans JP",
    ),
    font-features: (ss01: 1, ss02: 1, ss03: 1, zero: 1, tnum: 1),
    font-weight: 600,
  ),
  font-bold: (
    font-family: (
      (
        name: "Inter",
        covers: interFontCovers,
      ),
      "A P-OTF UD Shin Go Pr6N B",
      "Source Han Sans JP",
    ),
    font-features: (ss01: 1, ss02: 1, ss03: 1, zero: 1, tnum: 1),
    font-weight: 700,
  ),
  text-justify: (line-justify: true),
  text-no-justify: (line-justify: false),
  text-4xs: (text-size: q(6), line-spacing: q(9 - 6)),
  text-3xs: (text-size: q(7), line-spacing: q(10 - 7)),
  text-2xs: (text-size: q(8), line-spacing: q(11 - 8)),
  text-xs: (text-size: q(9), line-spacing: q(12 - 9)),
  text-sm: (text-size: q(11), line-spacing: q(14 - 11)),
  text-base: (text-size: q(13), line-spacing: q(20 - 13)),
  text-lg: (text-size: q(13), line-spacing: q(20 - 13)),
  text-xl: (text-size: q(14), line-spacing: q(20 - 14)),
  text-2xl: (text-size: q(15), line-spacing: q(20 - 15)),
  text-3xl: (text-size: q(16), line-spacing: q(20 - 16)),
  text-4xl: (text-size: q(20), line-spacing: q(20 - 20)),
  text-5xl: (text-size: q(24), line-spacing: q(24 - 24)),
  text-6xl: (text-size: q(28), line-spacing: q(28 - 28)),
  itext-4xs: (text-size: q(6)),
  itext-3xs: (text-size: q(7)),
  itext-2xs: (text-size: q(8)),
  itext-xs: (text-size: q(9)),
  itext-sm: (text-size: q(11)),
  itext-base: (text-size: q(13)),
  itext-lg: (text-size: q(13)),
  itext-xl: (text-size: q(14)),
  itext-2xl: (text-size: q(15)),
  itext-3xl: (text-size: q(16)),
  itext-4xl: (text-size: q(20)),
  itext-5xl: (text-size: q(24)),
  itext-6xl: (text-size: q(28)),
  border-0: (stroke-thickness: q(0)),
  border-1: (stroke-thickness: q(.5)),
  border-2: (stroke-thickness: q(1)),
  border-4: (stroke-thickness: q(2)),
  border-8: (stroke-thickness: q(4)),
  rounded-none: (radius: 0em),
  rounded-xs: (radius: q(9)),
  rounded-sm: (radius: q(11)),
  rounded-md: (radius: q(13)),
  rounded-lg: (radius: q(16)),
  rounded-xl: (radius: q(18)),
  rounded-2xl: (radius: q(20)),
  blrounded-none: (block-radius: 0em),
  blrounded-xs: (block-radius: q(9)),
  blrounded-sm: (block-radius: q(11)),
  blrounded-md: (block-radius: q(13)),
  blrounded-lg: (block-radius: q(16)),
  blrounded-xl: (block-radius: q(18)),
  blrounded-2xl: (block-radius: q(20)),
  bxrounded-none: (box-radius: 0em),
  bxrounded-xs: (box-radius: q(9)),
  bxrounded-sm: (box-radius: q(11)),
  bxrounded-md: (box-radius: q(13)),
  bxrounded-lg: (box-radius: q(16)),
  bxrounded-xl: (box-radius: q(18)),
  bxrounded-2xl: (box-radius: q(20)),
  ..color-style-tokens,
)

#let heading-token-params = (
  (
    heading-tokens: (style-tokens.text-3xl, style-tokens.font-semibold),
    lines-before: 0,
    lines-after: 0,
    line-feed: 2,
  ),
  (
    heading-tokens: (style-tokens.text-2xl, style-tokens.font-semibold),
    lines-before: 1,
    lines-after: 0,
    line-feed: 1,
  ),
  (
    heading-tokens: (style-tokens.text-xl, style-tokens.font-semibold),
    lines-before: 1,
    lines-after: 0,
    line-feed: 1,
  ),
  (
    heading-tokens: (style-tokens.text-lg, style-tokens.font-semibold),
    lines-before: 1,
    lines-after: 0,
    line-feed: 1,
  ),
  (
    heading-tokens: (style-tokens.text-base, style-tokens.font-semibold),
    lines-before: 0,
    lines-after: 0,
    line-feed: 1,
  ),
)
